# .github/workflows/download_and_replace.yml

name: Download and Replace

# 控制触发此工作流的事件
on:
  # 每当有推送发生时触发工作流
  push:
    branches:
      - main
  # 允许手动触发此工作流
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # 每天凌晨 2 点触发

jobs:
  download-and-replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Download apps.json from Nextcloud API
      run: |
        curl -o apps_ori.json https://apps.nextcloud.com/api/v1/apps.json
        curl -o discover_ori.json https://apps.nextcloud.com/api/v1/discover.json
        curl -o appapi_apps_ori.json https://apps.nextcloud.com/api/v1/appapi_apps.json
        curl -o categories.json https://apps.nextcloud.com/api/v1/categories.json

    - name: Replace github.com with github mirror in the JSON file
      run: |
        cat apps_ori.json | sed 's|github\.com|gh.llkk.cc/https://github.com|g' > apps.json
        cat discover_ori.json | sed 's|github\.com|gh.llkk.cc/https://github.com|g' > discover.json
        cat appapi_apps_ori.json | sed 's|github\.com|gh.llkk.cc/https://github.com|g' > appapi_apps.json

    - name: Commit changes and push to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "wangzihao2010@outlook.com"
        git config --local user.name "Error404"
        git add apps.json discover.json categories.json appapi_apps.json
        git commit -m "镜像原每日更新" || echo "No changes to commit"
        git push origin HEAD
